nome = input('Qual seu nome?\n')
dia = input('{}, em que dia voce nasceu?\n'.format(nome))
mes = int(input('{}, em qual mes voce nasceu?\n'.format(nome)))
ano = int(input('{}, em qual ano voce nasceu?\n'.format(nome)))
atual = int(input('Qual é o ano atual?\n'))
mesatual = int(input('Em qual mês estamos?\n'))
print('Ola {}! Você nasceu em {}/{}/{}, correto?'.format(nome,dia,mes,ano))
idade = float (((((12-mesatual)*atual)-(ano*(12-mes)))/12))
print ('Sua idade é {}'.format(idade))